# app/streamlit_app.py
from __future__ import annotations
import os, sys
import numpy as np
import pandas as pd
import streamlit as st
from collections import Counter
import pathlib
from fasta_processing import read_fasta_bytes, dnaOperations, rnaConverter, proteinOperations

# ===== Helpers for preview & HTML export =====
def wrap_seq(s: str, width: int = 60) -> str:
    return "\n".join(s[i:i+width] for i in range(0, len(s), width))

def html_table_from_df(df: pd.DataFrame) -> str:
    return df.to_html(index=False, escape=True)

def build_html_report(title: str, sections: list[tuple[str, str]]) -> str:
    # sections: list of (heading, html_content)
    css = """
    body{font-family:system-ui,Segoe UI,Roboto,Arial;margin:32px;}
    h1{margin-bottom:0.2rem} h2{margin-top:1.6rem}
    table{border-collapse:collapse;width:100%} td,th{border:1px solid #ddd;padding:6px 8px}
    th{background:#f6f6f6;text-align:left}
    code,pre{background:#f7f7f7;padding:8px;border-radius:6px;display:block;white-space:pre-wrap}
    .meta{opacity:.75;font-size:.9rem}
    """
    parts = [f"<html><head><meta charset='utf-8'><title>{title}</title><style>{css}</style></head><body>"]
    parts.append(f"<h1>{title}</h1><p class='meta'>Generated by Streamlit app</p>")
    for h, content in sections:
        parts.append(f"<h2>{h}</h2>")
        parts.append(content)
    parts.append("</body></html>")
    return "".join(parts)

SAMPLE_PATHS = {
    "DNA": pathlib.Path(__file__).resolve().parent.parent / "sampledata" / "example-dna.fasta",
    "RNA": pathlib.Path(__file__).resolve().parent.parent / "sampledata" / "example-rna.fasta",
    "Protein": pathlib.Path(__file__).resolve().parent.parent / "sampledata" / "example-protein.fasta",
}

def get_sample_bytes(mode: str) -> bytes:
    key = "DNA" if mode == "DNA" else ("RNA" if mode.startswith("RNA") else "Protein")
    return SAMPLE_PATHS[key].read_bytes()

st.set_page_config(page_title="FASTA Processing", page_icon="🧬", layout="wide")

# ============= SIDEBAR (left side-peek) =============
with st.sidebar:
    st.header("📥 Input & options")
    mode = st.selectbox("Analysis mode", ["DNA", "RNA→Protein", "Protein"])

    use_sample = st.toggle(
        "Use sample dataset",
        value=True,
        help="If enabled, a built-in example is loaded instead of your file."
    )

    if not use_sample:
        upl = st.file_uploader(
            "Upload FASTA file",
            type=["fa", "fasta", "fna", "faa", "fas"],
            help="One or more sequences in FASTA format."
        )
    else:
        upl = None  # we will read from sampledata/

    st.markdown("---")
    st.caption("Filters / charts")
    min_len = st.number_input("Min length", min_value=0, value=0, step=50)
    max_len = st.number_input("Max length (0 = no limit)", min_value=0, value=0, step=1000)
    bins = st.slider("Histogram bins", min_value=5, max_value=100, value=40)
    top_n = st.slider("Top N (codons/AA)", min_value=5, max_value=60, value=20)
    st.markdown("---")
    st.markdown("Developed by Michał Milewski")

st.title("🧬 FASTA Processing — stats & visualization")

with st.expander("What is a FASTA file? Click to see format details.", expanded=False):
    st.markdown(
        """
        A FASTA file is a plain-text format used to store biological sequences (DNA, RNA, protein).

        **Structure:**
        - Each sequence starts with a header line beginning with `>` followed by an identifier (and optionally a description).
        - The following lines contain the sequence itself (A/C/G/T or A/C/G/U for nucleotides, 20 letters for amino acids).
        - Lines are usually wrapped at ~60–80 characters, but wrapping is not strictly required.

        **Example (DNA):**
        ```
        >seq1 human mitochondrion
        ATGCTACCTCCTCAAGTACATGAGCTGTTGGCAG
        >seq2 E.coli plasmid fragment
        GCGTATGCTAGCTGATCGATCGTAGCTAGCATCGATCG
        ```
        """
    )

# ===== Resolve data source (sample or user upload) =====
if use_sample:
    data_bytes = get_sample_bytes(mode)
else:
    if not upl:
        st.info("Upload a FASTA file on the left, or enable the sample dataset.")
        st.stop()
    data_bytes = upl.read()

@st.cache_data(show_spinner=False)
def load_seqs(data: bytes) -> dict[str, str]:
    return read_fasta_bytes(data)

seqs = load_seqs(data_bytes)
if not seqs:
    st.error("No sequences found.")
    st.stop()

# (opcjonalnie) baner informacyjny
if use_sample:
    st.info(
        "Showing analysis for sample dataset: **{}** (from `sampledata/`).".format(
            "DNA" if mode=="DNA" else ("RNA" if mode.startswith("RNA") else "Protein")
        )
    )

# ============= HELPERS =============
def apply_length_filters(df: pd.DataFrame) -> pd.DataFrame:
    out = df
    if min_len > 0:
        out = out[out["length"] >= min_len]
    if max_len > 0:
        out = out[out["length"] <= max_len]
    return out

# ============= DNA MODE =============
if mode == "DNA":
    rows = []
    agg_counts = Counter()
    for sid, seq in seqs.items():
        try:
            dna = dnaOperations(seq)
        except ValueError as e:
            # skip invalid DNA record
            continue
        counts = dna.nuc_count()
        agg_counts.update({k: counts.get(k, 0) for k in ("A", "C", "G", "T")})
        rows.append(
            {
                "id": sid,
                "length": len(seq),
                "GC%": dna.gc_content(),
                "A": counts.get("A", 0),
                "C": counts.get("C", 0),
                "G": counts.get("G", 0),
                "T": counts.get("T", 0),
            }
        )
    df = pd.DataFrame(rows).sort_values("length", ascending=False).reset_index(drop=True)
    df_f = apply_length_filters(df)

    t1, t2, t3 = st.tabs(["Summary", "Distributions", "Details"])

    with t1:
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Sequences", f"{len(df_f):,}".replace(",", " "))
        c2.metric("Mean length", f"{df_f['length'].mean():.1f}" if len(df_f) else "–")
        c3.metric("Median length", f"{df_f['length'].median():.1f}" if len(df_f) else "–")
        c4.metric("Avg GC%", f"{df_f['GC%'].mean():.2f}" if len(df_f) else "–")
        st.dataframe(df_f, use_container_width=True)

        #per-sequence preview (original / complement / reverse-comp / RNA) ---
        if len(df_f):
            st.markdown("#### Preview sequence")
            picked_id = st.selectbox("Select sequence ID", options=df_f["id"].tolist())
            if picked_id in seqs:
                dna_prev = dnaOperations(seqs[picked_id])
                orig = seqs[picked_id].upper()
                comp = "".join(dna_prev.complement())
                revc = "".join(dna_prev.reverse_complement())
                rna  = "".join(dna_prev.transcribe_dna_to_rna())
                col_a, col_b = st.columns(2)
                with col_a:
                    st.caption("Original (5'→3')")
                    st.code(wrap_seq(orig), language="text")
                    st.caption("Complement (3'→5')")
                    st.code(wrap_seq(comp), language="text")
                with col_b:
                    st.caption("Reverse-complement (5'→3')")
                    st.code(wrap_seq(revc), language="text")
                    st.caption("Transcribed RNA")
                    st.code(wrap_seq(rna), language="text")

    with t2:
        st.subheader("Length histogram")
        if len(df_f):
            hist, edges = np.histogram(df_f["length"].to_numpy(), bins=bins)
            st.bar_chart(pd.DataFrame({"count": hist}, index=pd.RangeIndex(len(hist))))

        st.subheader("GC% distribution")
        if len(df_f):
            hist_gc, edges_gc = np.histogram(df_f["GC%"].to_numpy(), bins=bins, range=(0, 100))
            st.bar_chart(pd.DataFrame({"count": hist_gc}, index=pd.RangeIndex(len(hist_gc))))

        st.subheader("Global nucleotide composition")
        comp_df = pd.DataFrame.from_dict(agg_counts, orient="index", columns=["count"]).loc[["A","C","G","T"]]
        st.bar_chart(comp_df)

    with t3:
        st.download_button(
            "Download CSV",
            df_f.to_csv(index=False).encode("utf-8"),
            file_name="dna_stats.csv",
            mime="text/csv",
        )
        # --- HTML report export ---
        html = build_html_report(
            title="DNA Statistics Report",
            sections=[
                ("Summary metrics",
                 f"<ul>"
                 f"<li>Sequences: <b>{len(df_f)}</b></li>"
                 f"<li>Mean length: <b>{(df_f['length'].mean() if len(df_f) else 0):.1f}</b></li>"
                 f"<li>Median length: <b>{(df_f['length'].median() if len(df_f) else 0):.1f}</b></li>"
                 f"<li>Average GC%: <b>{(df_f['GC%'].mean() if len(df_f) else 0):.2f}</b></li>"
                 f"</ul>"),
                ("Per-sequence table", html_table_from_df(df_f)),
            ],
        )
        st.download_button("Download HTML report", html, file_name="dna_report.html", mime="text/html")

# ============= RNA → PROTEIN MODE =============
elif mode == "RNA→Protein":
    rows = []
    codon_usage_global = Counter()
    orf_lengths = []

    for sid, rna in seqs.items():
        conv = rnaConverter(rna)
        # protein 1-letter for compactness
        protein_seq = "".join(conv.rna_to_protein(one_letter=True))
        codon_usage_global.update(conv.analyze_codon_usage())
        for orf in conv.find_open_reading_frames():
            orf_lengths.append(len(orf))

        rows.append(
            {
                "id": sid,
                "rna_len": len(conv.rna_sequence),
                "aa_len": len(protein_seq),
                "protein (1-letter)": protein_seq[:200] + ("..." if len(protein_seq) > 200 else ""),
            }
        )

    df = pd.DataFrame(rows).sort_values("aa_len", ascending=False).reset_index(drop=True)
    # filter by length uses protein length here
    df_f = df.copy()
    if min_len > 0:
        df_f = df_f[df_f["aa_len"] >= min_len]
    if max_len > 0:
        df_f = df_f[df_f["aa_len"] <= max_len] if max_len > 0 else df_f

    t1, t2, t3 = st.tabs(["Summary", "Distributions", "Details"])

    with t1:
        c1, c2, c3 = st.columns(3)
        c1.metric("Sequences", f"{len(df_f):,}".replace(",", " "))
        c2.metric("Mean AA length", f"{df_f['aa_len'].mean():.1f}" if len(df_f) else "–")
        c3.metric("Median AA length", f"{df_f['aa_len'].median():.1f}" if len(df_f) else "–")
        st.dataframe(df_f, use_container_width=True)

    with t2:
        st.subheader("Protein length histogram")
        if len(df_f):
            hist, edges = np.histogram(df_f["aa_len"].to_numpy(), bins=bins)
            st.bar_chart(pd.DataFrame({"count": hist}, index=pd.RangeIndex(len(hist))))

        st.subheader(f"Top {top_n} codons")
        if codon_usage_global:
            codon_df = pd.DataFrame(codon_usage_global.items(), columns=["codon", "count"]).sort_values(
                "count", ascending=False
            ).head(top_n).set_index("codon")
            st.bar_chart(codon_df)

        st.subheader("ORF length histogram")
        if orf_lengths:
            hist_orf, edges_orf = np.histogram(np.array(orf_lengths), bins=bins)
            st.bar_chart(pd.DataFrame({"count": hist_orf}, index=pd.RangeIndex(len(hist_orf))))

    with t3:
        st.download_button(
            "Download CSV",
            df_f.to_csv(index=False).encode("utf-8"),
            file_name="rna_protein_stats.csv",
            mime="text/csv",
        )
        html = build_html_report(
            title="RNA→Protein Report",
            sections=[
                ("Summary metrics",
                    f"<ul>"
                    f"<li>Sequences: <b>{len(df_f)}</b></li>"
                    f"<li>Mean AA length: <b>{(df_f['aa_len'].mean() if len(df_f) else 0):.1f}</b></li>"
                    f"<li>Median AA length: <b>{(df_f['aa_len'].median() if len(df_f) else 0):.1f}</b></li>"
                    f"</ul>"),
                ("Per-sequence table", html_table_from_df(df_f)),
            ],
        )
        st.download_button("Download HTML report", html, file_name="rna_protein_report.html", mime="text/html")

# ============= PROTEIN MODE =============
else:  # Protein
    rows = []
    aa_global = Counter()

    for sid, aa in seqs.items():
        try:
            p = proteinOperations(aa)
        except ValueError:
            continue
        counts = p.count_amino_acids()
        aa_global.update(counts)
        rows.append(
            {
                "id": sid,
                "length": len(aa),
                "MW (Da)": p.molecular_weight(),
                "pI (approx)": p.isoelectric_point(),
                "Hydrophobicity": p.hydrophobicity_score(),
            }
        )

    df = pd.DataFrame(rows).sort_values("length", ascending=False).reset_index(drop=True)
    df_f = apply_length_filters(df)

    t1, t2, t3 = st.tabs(["Summary", "Distributions", "Details"])

    with t1:
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Sequences", f"{len(df_f):,}".replace(",", " "))
        c2.metric("Mean length", f"{df_f['length'].mean():.1f}" if len(df_f) else "–")
        c3.metric("Median length", f"{df_f['length'].median():.1f}" if len(df_f) else "–")
        c4.metric("Mean MW (Da)", f"{df_f['MW (Da)'].mean():.1f}" if len(df_f) else "–")
        st.dataframe(df_f, use_container_width=True)

    with t2:
        st.subheader("Protein length histogram")
        if len(df_f):
            hist, edges = np.histogram(df_f["length"].to_numpy(), bins=bins)
            st.bar_chart(pd.DataFrame({"count": hist}, index=pd.RangeIndex(len(hist))))

        st.subheader(f"Top {top_n} amino acids")
        if aa_global:
            aa_df = (
                pd.DataFrame(aa_global.items(), columns=["aa", "count"])
                .sort_values("count", ascending=False)
                .head(top_n)
                .set_index("aa")
            )
            st.bar_chart(aa_df)

    with t3:
        st.download_button(
            "Download CSV",
            df_f.to_csv(index=False).encode("utf-8"),
            file_name="protein_stats.csv",
            mime="text/csv",
        )
        html = build_html_report(
            title="Protein Statistics Report",
            sections=[
                ("Summary metrics",
                 f"<ul>"
                 f"<li>Sequences: <b>{len(df_f)}</b></li>"
                 f"<li>Mean length: <b>{(df_f['length'].mean() if len(df_f) else 0):.1f}</b></li>"
                 f"<li>Median length: <b>{(df_f['length'].median() if len(df_f) else 0):.1f}</b></li>"
                 f"<li>Mean MW (Da): <b>{(df_f['MW (Da)'].mean() if len(df_f) else 0):.1f}</b></li>"
                 f"</ul>"),
                ("Per-sequence table", html_table_from_df(df_f)),
            ],
        )
        st.download_button("Download HTML report", html, file_name="protein_report.html", mime="text/html")


st.caption("UI: Streamlit · Core logic: your `fasta_processing` package")