[theme]
primaryColor = "#1E88E5"          #  buttons, sliders
backgroundColor = "#F5F7FA"       #  background color
secondaryBackgroundColor = "#E3F2FD" # sidebar color
textColor = "#1F2937"             # TEXT
font = "sans serif"
